import type { HunkCategory, ParsedHunk, RiskReason } from "../types.js";
import { basename, extension, normalizeRepoRelative } from "../path-utils.js";
import { languageForPath } from "./languages.js";
import { isTokenFormatOnly } from "../structure/index.js";

const LOCKFILES = new Set([
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "bun.lock",
  "bun.lockb",
  "Cargo.lock",
  "poetry.lock",
  "uv.lock",
  "Pipfile.lock",
  "go.sum",
  "composer.lock",
  "Gemfile.lock"
]);

const DOC_EXTENSIONS = new Set(["md", "mdx", "rst", "adoc"]);
const CONFIG_EXTENSIONS = new Set([
  "json",
  "yaml",
  "yml",
  "toml",
  "ini",
  "cfg",
  "conf",
  "properties",
  "editorconfig"
]);

export interface Classification {
  category: HunkCategory;
  reason: string;
}

export function classifyHunk(
  hunk: ParsedHunk,
  reasons: RiskReason[],
  generatedPaths: Set<string> = new Set()
): Classification {
  if (hunk.isBinary) {
    return { category: "binary", reason: "BINARY_FILE" };
  }
  if (hunk.isRenameOnly) {
    return { category: "mechanical", reason: "RENAME_ONLY" };
  }
  if (hunk.lines.some((line) => /Subproject commit/i.test(line.text))) {
    return { category: "config", reason: "SUBMODULE_BUMP" };
  }

  const pathRule = classifyByPath(hunk, generatedPaths);
  if (pathRule.category !== "logic") {
    return pathRule;
  }

  if (pathRule.category === "logic" || pathRule.category === "config") {
    const mechanical = mechanicalRule(hunk, reasons);
    if (mechanical) {
      return { category: "mechanical", reason: mechanical };
    }
  }

  return pathRule;
}

function classifyByPath(hunk: ParsedHunk, generatedPaths: Set<string>): Classification {
  const file = normalizeRepoRelative(hunk.file);
  const lower = file.toLowerCase();
  if (isGeneratedPath(hunk, generatedPaths)) {
    return { category: "generated", reason: "GENERATED_PATH" };
  }
  if (isDependencyHunk(hunk)) {
    return { category: "deps", reason: isLockfilePath(file) ? "LOCKFILE" : "DEPENDENCY_MANIFEST" };
  }
  if (isTestPath(file)) {
    return { category: "tests", reason: "TEST_PATH" };
  }
  if (isDocsPath(file)) {
    return { category: "docs", reason: "DOCS_PATH" };
  }
  if (isConfigPath(file) || lower.startsWith(".github/")) {
    return { category: "config", reason: "CONFIG_PATH" };
  }
  return { category: "logic", reason: "DEFAULT_LOGIC" };
}

export function isGeneratedPath(hunk: ParsedHunk, generatedPaths: Set<string> = new Set()): boolean {
  const file = normalizeRepoRelative(hunk.file);
  const lower = file.toLowerCase();
  const base = basename(file).toLowerCase();
  if (generatedPaths.has(file)) {
    return true;
  }
  if (
    /(^|\/)(dist|build|\.next|out|vendor)(\/|$)/i.test(file) ||
    /(^|\/)__snapshots__(\/|$)/i.test(file)
  ) {
    return true;
  }
  if (
    base.endsWith(".min.js") ||
    base.endsWith(".min.css") ||
    base.endsWith(".map") ||
    base.endsWith(".snap") ||
    (base.endsWith(".lock") && !isLockfilePath(file)) ||
    base.endsWith("_pb2.py") ||
    base.endsWith(".pb.go") ||
    base.endsWith(".g.dart") ||
    lower.includes(".generated.")
  ) {
    return true;
  }
  const firstAdded = hunk.lines
    .filter((line) => line.kind === "add")
    .slice(0, 3)
    .map((line) => line.text)
    .join("\n");
  return /@generated|Code generated by/i.test(firstAdded);
}

export function isLockfilePath(filePath: string): boolean {
  return LOCKFILES.has(basename(filePath));
}

export function isManifestPath(filePath: string): boolean {
  const base = basename(filePath);
  return (
    base === "package.json" ||
    base === "pyproject.toml" ||
    /^requirements.*\.txt$/i.test(base) ||
    base === "Cargo.toml" ||
    base === "go.mod"
  );
}

export function isDependencyHunk(hunk: ParsedHunk): boolean {
  const file = normalizeRepoRelative(hunk.file);
  if (isLockfilePath(file)) {
    return true;
  }
  if (!isManifestPath(file)) {
    return false;
  }
  const visible = hunk.lines.map((line) => line.text).join("\n");
  const base = basename(file);
  if (base === "package.json") {
    return /"?(dependencies|devDependencies|peerDependencies)"?\s*:/.test(visible);
  }
  if (base === "pyproject.toml") {
    return /\[project\.dependencies\]|\[tool\.poetry\.dependencies\]/.test(visible);
  }
  if (/^requirements.*\.txt$/i.test(base)) {
    return true;
  }
  if (base === "Cargo.toml") {
    return /\[dependencies\]/.test(visible);
  }
  if (base === "go.mod") {
    return /\brequire\b/.test(visible);
  }
  return false;
}

export function isTestPath(filePath: string): boolean {
  const file = normalizeRepoRelative(filePath);
  const base = basename(file);
  return (
    /(^|\/)(test|tests|__tests__|spec)(\/|$)/i.test(file) ||
    /\.(test|spec)\./i.test(base) ||
    /_test\.go$/i.test(base) ||
    /^test_.*\.py$/i.test(base) ||
    base === "conftest.py"
  );
}

export function isDocsPath(filePath: string): boolean {
  const file = normalizeRepoRelative(filePath);
  const base = basename(file);
  const ext = extension(file);
  return (
    DOC_EXTENSIONS.has(ext) ||
    file.toLowerCase().startsWith("docs/") ||
    /^LICENSE/i.test(base) ||
    /^CHANGELOG/i.test(base) ||
    (ext === "txt" && !/^requirements.*\.txt$/i.test(base))
  );
}

export function isConfigPath(filePath: string): boolean {
  const file = normalizeRepoRelative(filePath);
  const base = basename(file);
  const ext = extension(file);
  return (
    CONFIG_EXTENSIONS.has(ext) ||
    base.startsWith(".env") ||
    base.toLowerCase().startsWith("dockerfile") ||
    base.toLowerCase().startsWith("docker-compose") ||
    base === "Makefile" ||
    file === ".gitlab-ci.yml" ||
    base === "Jenkinsfile" ||
    /^tsconfig/i.test(base) ||
    /^eslint/i.test(base) ||
    /^prettier/i.test(base) ||
    /^vite\.config\./i.test(base) ||
    /^next\.config\./i.test(base)
  );
}

function mechanicalRule(hunk: ParsedHunk, reasons: RiskReason[]): string | null {
  if (reasons.some((reason) => reason.weight >= 15)) {
    return null;
  }
  if (isWhitespaceOnly(hunk)) {
    return "WHITESPACE_ONLY";
  }
  if (isTokenFormatOnly(hunk)) {
    return "ast-format-only";
  }
  if (isCommentOnly(hunk)) {
    return "COMMENT_ONLY";
  }
  if (isImportReorderOnly(hunk)) {
    return "IMPORT_REORDER_ONLY";
  }
  return null;
}

function isWhitespaceOnly(hunk: ParsedHunk): boolean {
  const added = changedText(hunk, "add");
  const removed = changedText(hunk, "del");
  if (added.length === 0 || removed.length === 0) {
    return false;
  }
  return normalizeWs(added.join("\n")) === normalizeWs(removed.join("\n"));
}

function normalizeWs(value: string): string {
  return value.replace(/\s+/gu, " ").trim();
}

function changedText(hunk: ParsedHunk, kind: "add" | "del"): string[] {
  return hunk.lines.filter((line) => line.kind === kind).map((line) => line.text);
}

function isCommentOnly(hunk: ParsedHunk): boolean {
  const changed = hunk.lines.filter((line) => line.kind !== "context");
  if (changed.length === 0) {
    return false;
  }
  const language = languageForPath(hunk.file);
  return changed.every((line) => {
    const text = line.text.trim();
    if (text.length === 0) {
      return true;
    }
    if (language.lineComments.some((prefix) => text.startsWith(prefix))) {
      return true;
    }
    if (language.blockComments.some(([start, end]) => text.startsWith(start) || text.endsWith(end))) {
      return true;
    }
    return text.startsWith("*") || text === "*/";
  });
}

function isImportReorderOnly(hunk: ParsedHunk): boolean {
  if (hunk.astImportReorderOnly !== undefined) {
    return hunk.astImportReorderOnly;
  }
  const changed = hunk.lines.filter((line) => line.kind !== "context");
  if (changed.length === 0) {
    return false;
  }
  const language = languageForPath(hunk.file);
  if (language.importRegexes.length === 0) {
    return false;
  }
  if (!changed.every((line) => language.importRegexes.some((regex) => regex.test(line.text)))) {
    return false;
  }
  const added = multiset(changedText(hunk, "add").map((line) => language.importSpecifier(line)));
  const removed = multiset(changedText(hunk, "del").map((line) => language.importSpecifier(line)));
  return sameMultiset(added, removed);
}

function multiset(values: Array<string | null>): Map<string, number> {
  const map = new Map<string, number>();
  for (const value of values) {
    if (!value) {
      continue;
    }
    map.set(value, (map.get(value) ?? 0) + 1);
  }
  return map;
}

function sameMultiset(a: Map<string, number>, b: Map<string, number>): boolean {
  if (a.size !== b.size) {
    return false;
  }
  for (const [key, count] of a) {
    if (b.get(key) !== count) {
      return false;
    }
  }
  return true;
}
